# Generated by Django 3.2.20 on 2023-08-28 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_author_options'),
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_image_url', models.URLField(blank=True, max_length=1500, null=True)),
                ('author_image', models.ImageField(upload_to='')),
                ('about', models.TextField()),
                ('website_url', models.URLField(blank=True, max_length=1500, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.author')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['author'],
            },
        ),
    ]
