# Generated by Django 3.2.20 on 2023-08-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
